### ISSUE TITLE
Getting Error while loading dwords.p file

### ISSUE THREAD

**Issue by rakashi** [aditya1503/Siamese-LSTM#17]
Traceback (most recent call last):
  File "/home/bindu/Desktop/text similarity/Siamese-LSTM-master/SiameseLSTM.py", line 403, in <module>
    dtr=pickle.load(open("./dwords.p",'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)

**Comment by aditya1503** [comment]
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

**Comment by rakashi** [comment]
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
where  I have to set these properties, I tried by setting in bashrc file but I am still getting the same error again

I have installed h5py library also

Traceback (most recent call last):
  File "alignDraw.py", line 3, in <module>
    import h5py
  File "/home/monica/.local/lib/python2.7/site-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: /home/monica/.local/lib/python2.7/site-packages/h5py/_errors.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8

Please help me

**Comment by aditya1503** [comment]
are you using Python 3?
it works on Python 2

**Comment by LuckySherry** [comment]
try 
dtr=pickle.load(open("./dwords.p",'rb'), encoding='latin1')
